language: rust
rust:
  - stable

os:
  - linux
  - osx

before_script:
  - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features -- -D clippy::pedantic -D clippy::nursery
  - cargo test

notifications:
  email:
    on_success: never
