language: rust
rust:
  - stable
  - beta

os:
  - linux
  - osx

before_script:
  - rustup component add clippy
script:
    #- cargo clippy --all-targets --all-features -- -D clippy::pedantic -D clippy::nursery
  - cargo clippy -- -D warnings
  - cargo test

notifications:
  email:
    on_success: never
